version: "3"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storeDB
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
