# Definición del tipo Category
type Category {
    id: ID!
    name: String
    deletedBy: String
    updatedBy: String
    createdBy: String
    createdAt: String
    deletedAt: String
    updatedAt: String
    products: [Product]
}

# Definición del tipo Product
type Product {
    id: ID!
    name: String
    stock: Int
    description: String
    salesPrice: Float
    image: String
    category: Category
    deletedBy: String
    updatedBy: String
    createdBy: String
    createdAt: String
    deletedAt: String
    updatedAt: String
}

# Definición del tipo Provider
type Provider {
    id: ID!
    email: String
    fullName: String
    phoneNumberAgent: String
    agent: String
    deletedBy: String
    updatedBy: String
    createdBy: String
    createdAt: String
    deletedAt: String
    updatedAt: String
    shoppingOrders: [ShoppingOrder]
}

# Definición del tipo ShoppingOrder
type ShoppingOrder {
    id: ID!
    confirmed: Boolean
    dateDelivery: String
    totalCost: Float
    provider: Provider
    deletedBy: String
    updatedBy: String
    createdBy: String
    createdAt: String
    deletedAt: String
    updatedAt: String
    orderDetails: [ProductShoppingOrder]
}

# Definición del tipo ProductShoppingOrder
type ProductShoppingOrder {
    id: ID!
    amount: Int
    costPerUnit: Float
    shoppingOrder: ShoppingOrder
    product: Product
    deletedBy: String
    updatedBy: String
    createdBy: String
    createdAt: String
    deletedAt: String
    updatedAt: String
}

# Definición de las consultas
type Query {
    getCategory(id: ID!): Category
    getCategories: [Category]
    getProduct(id: ID!): Product
    getProducts: [Product]
    getProvider(id: ID!): Provider
    getProviders: [Provider]
    getShoppingOrder(id: ID!): ShoppingOrder
    getShoppingOrders: [ShoppingOrder]
    getProductShoppingOrder(id: ID!): ProductShoppingOrder
    getProductShoppingOrders: [ProductShoppingOrder]
}

# Definición de las mutaciones
type Mutation {
    # Mutaciones para Category
    createCategory(name: String!): Category
    updateCategory(id: ID!, name: String): Category
    deleteCategory(id: ID!): Category

    # Mutaciones para Product
    createProduct(name: String!, stock: Int, description: String, salesPrice: Float, image: String, categoryId: ID!): Product
    updateProduct(id: ID!, name: String, stock: Int, description: String, salesPrice: Float, image: String, categoryId: ID): Product
    deleteProduct(id: ID!): Product

    # Mutaciones para Provider
    createProvider(email: String!, fullName: String, phoneNumberAgent: String, agent: String): Provider
    updateProvider(id: ID!, email: String, fullName: String, phoneNumberAgent: String, agent: String): Provider
    deleteProvider(id: ID!): Provider

    # Mutaciones para ShoppingOrder
    createShoppingOrder(confirmed: Boolean, dateDelivery: String, totalCost: Float, providerId: ID): ShoppingOrder
    updateShoppingOrder(id: ID!, confirmed: Boolean, dateDelivery: String, totalCost: Float, providerId: ID): ShoppingOrder
    deleteShoppingOrder(id: ID!): Shopp
